### ISSUE TITLE
When you remap {backward} and {forward}, portal labels keys don't work

### ISSUE THREAD

**Issue by sergiornelas** [cbochs/portal.nvim#10]
For example, I have this setup. When I remap backward/forward, the labels keymap don't work

query = { "modified", "different", "valid", "grapple" },
	labels = { "j", "k", "h", "l" },
	backward = "<c-i>",
	forward = "<c-o>",
	integrations = {
		grapple = true,
	},

**Comment by cbochs** [comment]
https://github.com/cbochs/portal.nvim#configuration

> ```lua
>    ---Keycodes used for jumping forward and backward. These are not overrides
>    ---of the current keymaps, but instead will be used internally when a jump
>    ---is selected.
>    backward = "<c-o>",
>    forward = "<c-i>",
> ```

These are not meant to be remapped unless you have a good reason to. There are no default keymaps for Portal. For keymap suggestions, please see the [suggested keymaps](https://github.com/cbochs/portal.nvim#suggested-keymaps) section.
