### ISSUE TITLE
[Feature|Help request] Limit results from a single buffer

### ISSUE THREAD

**Issue by akinsho** [cbochs/portal.nvim#36]
Hi @cbochs,

So apologies if this falls more into the RTFM space than an actual feature request but one thing I'm trying to get from portal is the ability to only see jumps across buffers rather than several jumps in a buffer e.g. I essentially want a query for the change(and/or jump) list that shows only one change per buffer similar to how I might use the tagstack to jump between definitions and back out. 

I know that you can add filters to portal queries but I can't find an easy way to say, "don't give me more than one result from a buffer" or/additionally how to specify how many results I get back.
At the moment it's entirely dependent on my cursor position so if I'm unlucky enough to be at the bottom of a buffer I'll only get a few (FWIW I work on a laptop almost exclusively so not much real estate)

Hopefully what I'm trying to achieve makes sense 🙏🏾

**Comment by cbochs** [comment]
Hey @akinsho!

Sure thing. I think what you're looking for is some sort of "stateful" filter. In this case, you can do something like:

```lua
---Return a stateful search predicate
---@return Portal.SearchPredicate
local function different()
    local found = {}

    ---@param content Portal.Content
    ---@return boolean
    return function(content)
        if vim.tbl_contains(found, content.buffer) then
            return false
        end
        found[#found + 1] = content.buffer
        return true
    end
end
```

And use it like:

```lua
require("portal.jumplist").tunnel_backward({ filter = different() })
```

README References:
- [builtin `jumplist`](https://github.com/cbochs/portal.nvim#jumplist)
- [`Portal.SearchOptions`](https://github.com/cbochs/portal.nvim#portalsearchoptions)
- [`Portal.SearchPredicate`](https://github.com/cbochs/portal.nvim#portalsearchpredicate)
- [`Portal.Content`](https://github.com/cbochs/portal.nvim#portalcontent)

**Note**: the [`:h changelist`](https://neovim.io/doc/user/motion.html#changelist) is a bit different since its buffer-local rather than window-local. You would need to aggregate a single result from all of the changelists, which might be a bit difficult.

**Comment by akinsho** [comment]
Actually I just made it my default `filter` would be still curious to know if they could have been composed together somehow without copy pasting but will close this out as my main issue is resolved 👍🏾

**Comment by cbochs** [comment]
> One question though is that I find that it replaces the default filter I have in place

Oh, interesting. [That shoudldn't happen](https://github.com/cbochs/portal.nvim/blob/main/lua/portal/builtin/jumplist.lua#L52-L60), both the settings (default) filter and your filter should be respected. Would you mind sharing what you tried? This is one setup that worked for me:

```lua
require("portal").setup({
    filter = function(content) return content.buffer ~= vim.fn.bufnr() end,
})

local function different()
    local function different()
        local found = {}
        return function(content)
            if vim.tbl_contains(found, content.buffer) then
                return false
            end
            found[#found + 1] = content.buffer
            return true
        end
    end
end

vim.keymap.set("n", "<leader>jb", function()
    require("portal.builtin").jumplist.tunnel({ filter = different() })
end
```

> but noticed there are also slots which seem similar to filters but are not

The idea behind slots is to allow you to pick _exactly_ what should appear for label "x". For example,
* label "j" should be my previous "modified" buffer
* label "k" should be my previous "grapple" buffer
* etc.

> I guess there's no way to combine filters in a list?

Do you mean providing a set of filters, akin to:

```lua
-- Doesn't currently work
require("portal.builtin").jumplist.tunnel({ filter = {
    function(content) return vim.fn.bufnr() ~= content.buffer end,
    function(content) return content.type == "grapple" end,
    -- ...
}})
```

**Comment by akinsho** [comment]
@cbochs yeah I mean the list of filters wasn't possible although maybe not massively necessary unless someone has several they want to run together which I guess I do but in my case just a the default combined with the different applied adhoc

Re. the combination not working I just had the different as a filter per call similar to your example and it included results from outside the current nvim directory but now I'm also not sure if my homegrown rooting logic had actually kicked in. 

I've not seen it recur yet so will assume it was my error unless it comes back in which case I'll post back on here.
