### ISSUE TITLE
[Feature request] Open portals in the direction with the most space

### ISSUE THREAD

**Issue by akinsho** [cbochs/portal.nvim#38]
Hi @cbochs 

Apologies for the multiple issues. I closed the last one and realised there was a point in there that I thought deserved it's own issue which is that, currently portal will always try and open the windows below your cursor rather than check if there is more space above or below and using the most appropriate direction.

e.g.
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/22454918/227579712-8c2f6d59-ea4f-4ade-9d48-27a20f7863a8.png">

In the example above there is tons of space above the cursor and almost none beneath it but the windows still try to open where there isn't much space

**Comment by cbochs** [comment]
Hah, this has also bugged me. I just hadn't spent the time to fix it. Just added a quick offset adjustment in e0ef8025e9041e6c72381b3b5802679da99d1481 to stop the windows from stacking on one-another
